/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/orders/{orderId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieve an order by Shopify order ID */
        get: operations["orderEdit.show"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/edit/begin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Begin editing an order. Returns the calculated order from Shopify */
        post: operations["orderEdit.begin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/edit/commit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Commit an order edit. Returns the updated order */
        post: operations["orderEdit.commit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BeginOrderEditRequest */
        BeginOrderEditRequest: {
            order_id: string;
        };
        /** CommitOrderEditRequest */
        CommitOrderEditRequest: {
            edit_id: string;
        };
    };
    responses: {
        /** @description Validation error */
        ValidationException: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @description Errors overview. */
                    message: string;
                    /** @description A detailed description of each field that failed validation. */
                    errors: {
                        [key: string]: string[];
                    };
                };
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "orderEdit.show": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orderId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            id: string;
                            name: string;
                            email: string;
                            created_at: string;
                            updated_at: string;
                            line_items: {
                                id: string;
                                title: string;
                                quantity: number;
                                price: string;
                            }[];
                        };
                    };
                };
            };
        };
    };
    "orderEdit.begin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BeginOrderEditRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            id: string;
                            order: {
                                id: string;
                                name: string;
                            };
                            line_items: {
                                id: string;
                                title: string;
                                quantity: number;
                                price: string;
                            }[];
                            added_line_items: {
                                id: string;
                                title: string;
                                quantity: number;
                                price: string;
                            }[];
                        };
                    };
                };
            };
            422: components["responses"]["ValidationException"];
        };
    };
    "orderEdit.commit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommitOrderEditRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            id: string;
                            name: string;
                            email: string;
                            created_at: string;
                            updated_at: string;
                            line_items: {
                                id: string;
                                title: string;
                                quantity: number;
                                price: string;
                            }[];
                        };
                    };
                };
            };
            422: components["responses"]["ValidationException"];
        };
    };
}
